version: '3'
services:
  app:
    image: node:12.4
    command: npm run develop
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    working_dir: /home/node
    volumes:
      - .:/home/node
